openapi: 3.0.0
info:
  title: GitHub API
  version: 1.0.0
paths:
  /repositories/{username}:
    get:
      summary: Get a list of user repositories
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        '406':
          description: Header not set
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
components:
  schemas:
    Branch:
      type: object
      properties:
        name:
          type: string
        sha:
          type: string
    Repository:
      type: object
      properties:
        repositoryName:
          type: string
        ownerLogin:
          type: string
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
    ApiException:
      type: object
      properties:
        status:
          type: string
        message:
          type: string